apiVersion: v1
kind: Secret
metadata:
  name: nix-collector-secret
type: Opaque
stringData:
  CONFIG_TOKEN: ENC[AES256_GCM,data:ygcqYYLstmrYsrhGSZJjmx1JIvpHwPcXY6k6HkEnHqbfyX9QTLOYbwEwPQ==,iv:WVMxNJ/jI8Ex3WMYH7QWRBxh2nwnOENpn31YAy1br20=,tag:vqhbstdhP8y3kr/hHadDMw==,type:str]
  CONFIG_INSTANCE: ENC[AES256_GCM,data:kqmootEhP1y3uNxe6gLTe8tlPPgwDnb6lWsUym28kG66Kzn1SnKsXrrOWJ/DdPwojQZTsU5g,iv:XOETSAqo+txi6y4iD1SH52e2R1PLILnYA0EoYjAICtY=,tag:krjb5IuWcd6ApUCLcSUF3w==,type:str]
  CONFIG_NAME: ENC[AES256_GCM,data:a7W6zzaaQjdLTlcLbg==,iv:+EwxwsuDZbai3pGquseyHNCwZKovoBFVSFsXqNlkld8=,tag:ybWnKzfMHHa33o6C+K23VQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPY2VrcXdkQjBEOTgzdVAx
        a3F2Nm4zZjZHZmdXWEorTFNEQ0IxMGpBN0Y0CmpaTzlhcmxINEJqekErczlxSkZh
        Yk8zNGhneGpEYmRLZnRrWUkvdDJlclUKLS0tIGZWOFlJME9tdHU4OUJhejRXU3lV
        c1dkWVVnYUU5cHkxejBaQS9yRVJuTFUK+/u06/DUaYoH+iRYuH/1pTssvABSMv56
        8YbOPd8EWmqBm23XS9+kXW6BM9vUurYe/LBJCwVeAnvzS+iY2+CKtQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T10:53:02Z"
  mac: ENC[AES256_GCM,data:VcT0CfeUCHCBzZLRgdUuLnV8S6976EdWDhEIGKDNJGeWxYkwDD4Pxn3fnhmCEuL4GtKuxN8zG13gunjuK4gcfP+8szZ1lVzbQq9xPjPjZuJTRequ92IImf2MmikfCx4XZvDk18r7jNCJTkmpiNabW6IR/Fvo0Dt8in4+xgmPXGU=,iv:XddQtzf9am/Z+wfE+98Y0L5cV07skfzogVYsYXc+uTE=,tag:FBDfCCj3PjOBuWAfe8eSLg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
