k8s-sing-box:
    age-private-key: ENC[AES256_GCM,data:6fSMZWQDrFf7HTOvhA7YHmPijvGQAU4Aw4j1myxHwdw3HXtmfqYrP2uw8Mlgdv6tq0+KG7pANKkybRLLXyguhiHwwACnTMkcHX0=,iv:/omsn6AD/RsqAs2C18CPiYMTT3QTaAeWZADAS4uJ7d0=,tag:75MzpPE/Mt3O/9aXyGsqjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQ3RhQjQ1M2paNHc3N1RY
            TmtxV0tOMWE4Y0drUENUUnRkRlpzQUNuT0J3CnhzNzNVOEMzS0JNWmlEY0hIci85
            V3gwYVFFTllQajRyK3NUVlhmSVdOYk0KLS0tIGhrMzZwSnZRQ3hURU9YM3ZEYlJY
            WXlTbGZpNVBOcWVraEFiR1ZaK1AzakUKktTcYW503IIyKY46Dz0aiLh8dVCiLDav
            /7VKlQTNxraqbqei56EiIRv2bazRo+aBWjP/SmDGQ14T16Ds2TVJjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ypc5zlh0zemv904jlpltlfqs8g0q6yh03xp4uamtenxpkzx4news3gemxk
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUXdaNE94QjBqV2RCaU5S
            MG5UazNsRlpzL3ByajdKcGw3RnVVQVUrTkZ3CnFEcWRXQTZtSlFqRHRvRXlacGNz
            Z1p6THZmSFkvTVlhV2RZSkE4T2NZNEEKLS0tIDhLODVYQkhPZUJ2aW5hdkpKMjBJ
            eHYrQ1krZ2J4VXNZWmFNS3RsSzVXeHMKTApcmSFvs1giv57bHd236srXYW4b9X3l
            Gnr6mmNn490E/IU0NN+jEzY9/t339Ie2vXQYTDbAdWQIpqMcKMtzng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age198u72xdclycdl00k0yhl7acxuc4wus7sgnwane7mvht34uvsyeeqxn38mu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONEFZQ2VqMjNmbXdRT0l6
            QlhKRVdpUk1IdEVHY2JQeGY3REFVOWFjTW5jCkRlYVRTWWtSVTRjZzRiakdRb1pZ
            QTBqZFdVYnhCK2hROTZpcTBlTzFFTWMKLS0tIFl1MkVGR3Vkc2RxdktRaVN1OVZm
            WnUwYjcycWw4T3l3UysraW5HdXRxUGsKA5RcoXR5vu/9OobnGijz8fSLDl5eiyR3
            iCy6hVuTOeMVd8hEl/N3B2HrOm6kRenR5Q8+A9artbuIdpRekaaIrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z3ze2hu0j2pe0t3nyt0u42w5f4wkajg5dp203az03kep0ze9c4fszlar25
    lastmodified: "2026-03-14T03:58:56Z"
    mac: ENC[AES256_GCM,data:LPrJwaLscfoUs3WLM5ZCsa2BVPKWQi0fhXLG9MD5s2vmk4+0ZCfSxOIc6gvOB/9ZWjMYSInUG/Bwee4E+wI/Hxw5loIjQoUJRVSxVqsZJY3OIAdUFzvz0mCcHpxRyc/jprJvVMvU5xf9kk4iWzjuo7TMJkgk+L8x5kk6rvt01zc=,iv:yUUGBpZE4dBWKEHpjH2Iz2OlaQhqRtfcI0lO8gCwgHY=,tag:TMsTaKuR8MA0OFAabMC9Bg==,type:str]
    pgp:
        - created_at: "2026-08-13T13:08:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DTahU1jzz8zoSAQdA0d7hU7KbQ1e3z4uz5sGy89oy5z8Zp+OgLBhAlpI0rUIw
            3GXzZFgV/PX9eQ1qrKpWuwXakbWMwQMhMS48bglCOA9AtMVkNpnSVYvgXkYMCmub
            0l4Be/J0swNWUb62cpLSESsbshkstpySW5+FKVjtKm/TBXaRTl+mHou4+tdW9Fr5
            aXHuZKe3UiV3lb408uG6MXySk03qX1TvkrbRkNt81vR3HggQjPUW7c5Tijhi0B8L
            =oLvw
            -----END PGP MESSAGE-----
          fp: 65C80FDF47908160E7F30FBE58FCE01334F49CA9
    unencrypted_suffix: _unencrypted
    version: 3.12.1
