name: Check Secrets

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: nix-builder
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Test secret checks
        run: >-
          nix-shell -I nixpkgs=flake:nixpkgs
          -p 'python3.withPackages (ps: [ ps.pyyaml ])'
          --run 'python3 utils/test-check-secrets.py'
      - name: Check tracked content
        run: >-
          nix-shell -I nixpkgs=flake:nixpkgs
          -p 'python3.withPackages (ps: [ ps.pyyaml ])'
          --run 'python3 utils/check-secrets.py'
