---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ai
  - ./archive
  - ./cert-manager
  - ./collaboration
  - ./database
  - ./default
  - ./development
  - ./flux-system
  - ./identity
  - ./kube-system
  - ./monitoring
  - ./network
  - ./nix
  - ./nix-check-runner
  - ./nix-collector
  - ./registry
  - ./storage
