apiVersion: v1
kind: Secret
metadata:
    name: multica-secrets
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:Bit33AbVDGEcQCEZknDKCSwAFG0FwDjGbp4x0KBQtSegrEDp8TEgptsZ1KCBB0eME9rD8tzG4lXqd0n+id0x8A==,iv:/lM+S887NbINFgnaTCZF7r9XEON+qjNDqRr+J0JN9Pk=,tag:FfyAUe5BIZ3LUzvZnTUsYA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:JVWrbUcF4Gjn+nmj4nm3VapKoiRuDbeVRhqpkyOxItbrjXQ3Y1QvXoxQgs75C2cog7HWG+HyLo2EboqrrOyGsOwuMF5BcEdwCfXkkVK7VKgLwe/y07EAn0SI6MFq8EqmvCq9NX1TEurD0kAxoGuyeSFCuyexzPJXg4ELGfqYDsaxK9ohwQpy3bY9fmt0fRz66ma2aXuchrolQ3lJ,iv:FtVLUlGCtId+roez7V18S+HDlxjfygef0wKaoEHT1Io=,tag:LfJH77WTGSTvLFamztD1fA==,type:str]
    MULTICA_VCS_SECRET_KEY: ENC[AES256_GCM,data:MYW/0EaVFn0f+6o6YknjTVhz5MejuDdUe8coDMB6DY1Ic3p6tQv79HVQJ5U=,iv:WxC+lECNbj0iXnZFIumVYzVG+bG8KG3iVPemlFMBabo=,tag:TOA4MNZELzRGUPxe9k5qCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycXVVSDU2bXY1YUFIZExR
            QU9lYTNsMDQ1clBXNjRhaUJ2SmFhNTBOYzF3Ck5NUTRRYnRkMDlTMWZPaG5XbVVl
            MjA3ZDBQdU9Da0F0YkwzbHJWUi9ZVkUKLS0tIGJaZEtuTUQzcElvMWhjcDFYdmN6
            OVVFaFlEbWhpd1BJbXNuTU9XR1JZb1UKSihZeEqh2b01RSet6trijSbZu4g0E/rL
            xV2M7qin9W1ZS0mF3Cddx0y1YYtH5r4VO6uQgOZDIvcgQSPXXaiLGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T11:29:59Z"
    mac: ENC[AES256_GCM,data:UvDZl6a2wt4viS6uxOnL6MDLXdExhR7HPo4IMIEs+KcJVa6hctOt3NyJaqJmcDuWKdWXHbaGse8SMAQsI4c5qA2fa08Z7/l54LKeJQAC1jbnXvTFhPSj6Y+tdF+qYRHrb+OeqfNPLPJP0ixaDedQll6++2BAtKyVtnta4f+FWwk=,iv:Xr/7wiziXF4KjTAPL3PQJgGlLyLw57WN6TPqycJ5Fp8=,tag:9F9EQmjZkCjGyMuGVOLccw==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
