apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-attic-netrc
stringData:
    netrc: ENC[AES256_GCM,data:QT7zli916Y4oLM703BsChiw1rZr/3Ca7l5q0oWbNjHdHGWoNHk1nb2MMqzZxDCYJgGIxbODd3S90h+Xb1lqcjnbD5iC3kcoELWq9EUs5nm6/sYhuyMOPP3yVkFdbcb7mPvngVZKZvufUTHtAx6lz+ZxRk31o4IqMkcjW5gYYGDI37XeRC122aWRnXZpERkmB63XI+MIMPWCVimpvk67rKeiFDEtcKIwjkJLRamm1V7dMCNo9nT8dCuMhzGUzPdSqQPKvPhLxWAYqfczQwKZl7YvLl3Q/N2CJq/ru7/MmlM+hcdDnFhAE8GP9swuivgmaLoU/jhvpL7rGYgMuPHgzTLkP62NwvPsri6WDop6eUak0C1MCRqDR2orMPD2LL0j6nOaAOLjtH2FtbjQlLMnR8wNkRktUIJ9zEgJr+knJ55xZi358KgqYbb/9x9NcpFeEn0SoFEReCLj59oKUKIGNLt1lIBbvmCUpV7C2S0EXpZaZ1shsOGjF6SMZcC8Aylm//93ujSugF0x4yMg1jXALNJbyI7Ng6JUmMFOKwWpbQZyJ7Ynv8lwKLcFh0Up69gB9bQ0vWycroBBWzma2/VO6tF0xA1UiGJffncjL8LRxz1X2hRQ4isfu0mWUNs4Ccl0KGGbD7ji/CCjEdE8MZ53IYPsArT6YwvXsPEPGYk+S3AGvLOWWVF+QbR/iHY8dkZMpNNWPdP9MxFDJmjw2tmPuEEb8GAb99ice5PnJQJmVX9w/Yts2UuPb9RDbve4D0WdYMnd0+HsKxFYAzOyaOdQThPgqou5d+OojbNu3zKBDyInLdiLSC+hJkQBMpbblptn6QD4JoR3nLXv3/x/Iil2PYV7LslMQ3E5okeONluN9ox3/UvLOIPmpNkUkMkZ8cFya2wJiSTO1lmXGaqhdHyeBFv3zmMXOvK0SEo/zIW7LccCtCBY/dBVC77ZyZHOYoK52wxY3I5n1RQQdJbwyKptWhCOjbxyOBEtJ1O2BHHL4cWwv4PiIrwTSN4zxepAGD1IUManGdl7NNbo3AZWX7Fhrn4hUjvox5p9ulbQ69LA4TsCNXgDkSwTqNs12sakJHvONjWD11u8fvB0cAlH5MuTd3W2UbkLxSS2qBZtRNCPiAz4bYwgwHxmMOdCCTiNhg2UmYVS/U8svj2zju2eROsrjqczfiYsIUrBIBMD3iAtzQOUkBa+jJC2ELsuaAzbeHFoCw+hXvkS8MRPwEhp/hfsCJ/LIAtfjl7iuprLImmrR,iv:ArDvbZTybDspeUFEAojuIxDE3Es4rOr0AqdsIinIH5M=,tag:2gwPmuPVSfXuCqKPhhYK4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UHM4WnNVQldqOVFDdDF4
            MU90ZmhYOVQ2ZmVJQmRXZ29pM2NpRXF4U1c4CjhFZUI4dFFQR3hSWGp6ZGxrZHhu
            RS9lUDZWOTRFbmhweGo2SFA1NDZQTVUKLS0tIHdXSzE0ZkR2SmZXT1FQMEU4dTNW
            S1ZQWXA2UXBPRGpob0FXTW9sSmFBcGcKpq1GfnUnvLthTBOOD2+U52OlwRtnteBc
            qbYhELF2wGbWAOEl70zQvX83XjCGKwycDbxvoiSos09RMBv0CrbqUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T19:42:14Z"
    mac: ENC[AES256_GCM,data:7gyY8X1my5tAhmTe2UxYalCm1aEGwSYW/jbdZeFdk+4quexlYZ5TxqRioZCkRwjTxd/80Xivt58eNYlvZZce2IjttQnCR6KH95J570I61eBr74u1Z9/C4FJWg+sfD1aSRFR2VDdacOMsplWvTs2ByPhb2TxhhURMVJw0nF6vuII=,iv:OH22K3KQ2ZYJY0aXCf6frKZJKqDUUt2G8+ncodGcLuI=,tag:MAmr8DZW7h5Rs6kU2IjaXw==,type:str]
    version: 3.13.3
