apiVersion: v1
kind: Secret
metadata:
  name: archivebox-secret
stringData:
  admin-password: ENC[AES256_GCM,data:8CK6DvCTYqJ+mstnhp/rP6N0V1Z7djwIGuAxZ/oJInw=,iv:D5UqzqDiL33MZkMeXaPUCHtNDoQwKOBHVMSOjY8E4XM=,tag:YZDZfLhHNMIaKCMsw1wKEA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNUZKQ1h4VitMWjU2U3VW
        akZVYVFKNTAyYzBabFlhNXo2aXFTdjRaNDBrCllLRzYrUitFSlNnVDRYUXFsdDdR
        K0Y4SWlKRGs5SGhqdFFSMlVUenRVS0kKLS0tIEJBdHo3T2Q5NEN2d09vQTdEVHA1
        RmVtbmJSN3pmRU0yOFhXM1VkKzVuYlUK5/HsQS8QzngRYeRwTVqcQxtMknlEUOw8
        c67GxNzIxyAH3Wt9qZ2r3oO0tOdhfJdc+n1P4ZjnZ/DxMu4xMthMCA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19w3svwspecedu893ges7te9qc5qgj3r5tykpkqrl43f90ndlvg4qant4ej
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T06:37:31Z"
  mac: ENC[AES256_GCM,data:QgWNTZ0Qfd98n1xMar57x4OOwE5tP0gcwXwGbjDIiHqxXHHV/kD1rsg7hz1e2C9i4NG5hhTuIQyC93KKIgSYysHTJTeqUpspFtuRr+7rxWypfdXqJvnWLfSQWReO3u+JbtDicpd2Hs0fwaD5d1UGXK4pWtJWjMUNGi4CfVh93gw=,iv:EHtLJhYzQunss8/1XglWZsrf6GHmAzYHXbwPBf5i9qQ=,tag:FLD03N/dyCoR4nEifIuVAA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
